modLoader="javafml"
loaderVersion="[32,)" #forge version dep
issueTrackerURL="https://github.com/iChun/Shatter/issues"

[[mods]]
    modId="shatter"
    version="${file.jarVersion}" #mandatory
    displayName="Shatter"
    displayURL="https://ichun.me/mods/shatter/"
    authors="iChun"
    description='''
    This mod adds a new death animation. Mobs die, their bodies wrecked, and souls shattered, they just seem to fade away. Weee~~~
    '''

[[dependencies.shatter]]
    modId="ichunutil"
    mandatory=true
    versionRange="[9.0.0,10)"
    ordering="NONE"
    side="BOTH"
